# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LearningBraille' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearningBraille
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'RxSwift',    '~> 4.0'
    	pod 'RxCocoa',    '~> 4.0'
	pod 'R.swift'

  target 'LearningBrailleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearningBrailleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
